/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.texteditor.menu;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;

/**
 *
 * @author Admin
 */
public class menuFrm extends javax.swing.JFrame {
private String text;
private static final int FONT_SIZE = 14;

    /**
     * Creates new form menuFrm
     */
    public menuFrm() {
        initComponents();
        setLocationRelativeTo(null);
        text = txtContent.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupColor = new javax.swing.ButtonGroup();
        btnGroupFontSize = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemEditText = new javax.swing.JMenuItem();
        menuItemRemoveText = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cbMenuItemUpper = new javax.swing.JCheckBoxMenuItem();
        cbMenuItemBold = new javax.swing.JCheckBoxMenuItem();
        cbMenuItemUnderline = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        menuItemRed = new javax.swing.JMenuItem();
        menuItemBlue = new javax.swing.JMenuItem();
        menuItemGreen = new javax.swing.JMenuItem();
        menuItemBlack = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rbtn150 = new javax.swing.JRadioButtonMenuItem();
        rbtn125 = new javax.swing.JRadioButtonMenuItem();
        rbtn100 = new javax.swing.JRadioButtonMenuItem();
        rbtn75 = new javax.swing.JRadioButtonMenuItem();
        rbtn25 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEXT EDITOR");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEXT EDITOR");

        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtContent.setLineWrap(true);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jMenu1.setText("File");

        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/save-24px.png"))); // NOI18N
        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSave);

        menuItemEditText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemEditText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/pen-24px.png"))); // NOI18N
        menuItemEditText.setText("Edit Text");
        menuItemEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditTextActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEditText);

        menuItemRemoveText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemRemoveText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/delete-24px.png"))); // NOI18N
        menuItemRemoveText.setText("Remove Text");
        menuItemRemoveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRemoveTextActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRemoveText);
        jMenu1.add(jSeparator1);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/turn-off-24px.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Style And Color");

        cbMenuItemUpper.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cbMenuItemUpper.setText("Upper");
        cbMenuItemUpper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/upper-text.png"))); // NOI18N
        cbMenuItemUpper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenuItemUpperActionPerformed(evt);
            }
        });
        jMenu2.add(cbMenuItemUpper);

        cbMenuItemBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cbMenuItemBold.setText("Bold");
        cbMenuItemBold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/bold-type.png"))); // NOI18N
        cbMenuItemBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenuItemBoldActionPerformed(evt);
            }
        });
        jMenu2.add(cbMenuItemBold);

        cbMenuItemUnderline.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cbMenuItemUnderline.setText("Underline");
        cbMenuItemUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/underlined-text.png"))); // NOI18N
        cbMenuItemUnderline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenuItemUnderlineActionPerformed(evt);
            }
        });
        jMenu2.add(cbMenuItemUnderline);
        jMenu2.add(jSeparator2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/dropper-16px.png"))); // NOI18N
        jMenu4.setText("Color");

        menuItemRed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/red-16px.png"))); // NOI18N
        menuItemRed.setText("RED");
        btnGroupColor.add(menuItemRed);
        menuItemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRedActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemRed);

        menuItemBlue.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/blue-16px.png"))); // NOI18N
        menuItemBlue.setText("BLUE");
        btnGroupColor.add(menuItemBlue);
        menuItemBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBlueActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemBlue);

        menuItemGreen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/green-16px.png"))); // NOI18N
        menuItemGreen.setText("GREEN");
        btnGroupColor.add(menuItemGreen);
        menuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGreenActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemGreen);

        menuItemBlack.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/texteditor/images/black-16px.png"))); // NOI18N
        menuItemBlack.setText("BLACK");
        btnGroupColor.add(menuItemBlack);
        menuItemBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBlackActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemBlack);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Font Size");

        rbtn150.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnGroupFontSize.add(rbtn150);
        rbtn150.setText("150%");
        rbtn150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn150ActionPerformed(evt);
            }
        });
        jMenu3.add(rbtn150);

        rbtn125.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnGroupFontSize.add(rbtn125);
        rbtn125.setText("125%");
        rbtn125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn125ActionPerformed(evt);
            }
        });
        jMenu3.add(rbtn125);

        rbtn100.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnGroupFontSize.add(rbtn100);
        rbtn100.setSelected(true);
        rbtn100.setText("100%");
        rbtn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn100ActionPerformed(evt);
            }
        });
        jMenu3.add(rbtn100);

        rbtn75.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnGroupFontSize.add(rbtn75);
        rbtn75.setText("75%");
        rbtn75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn75ActionPerformed(evt);
            }
        });
        jMenu3.add(rbtn75);

        rbtn25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        btnGroupFontSize.add(rbtn25);
        rbtn25.setText("25%");
        rbtn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn25ActionPerformed(evt);
            }
        });
        jMenu3.add(rbtn25);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        // TODO add your handling code here:
        text = txtContent.getText();
        txtContent.setEditable(false);
        
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGreenActionPerformed
        // TODO add your handling code here:
        txtContent.setForeground(Color.green);
    }//GEN-LAST:event_menuItemGreenActionPerformed

    private void cbMenuItemUnderlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenuItemUnderlineActionPerformed
        // TODO add your handling code here:
        if(cbMenuItemUnderline.isSelected()){
            Font font = txtContent.getFont();
            Map att = font.getAttributes();
            att.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
            txtContent.setFont(font.deriveFont(att));
        }else{
            Font font = txtContent.getFont();
            Map att = font.getAttributes();
            att.put(TextAttribute.UNDERLINE, -1);
            txtContent.setFont(font.deriveFont(att));
        }
    }//GEN-LAST:event_cbMenuItemUnderlineActionPerformed

    private void rbtn125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn125ActionPerformed
        // TODO add your handling code here:
        if(rbtn125.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), txtContent.getFont().getStyle(), (int) ((int) FONT_SIZE*1.25)));
        }
    }//GEN-LAST:event_rbtn125ActionPerformed

    private void rbtn75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn75ActionPerformed
        // TODO add your handling code here:
        if(rbtn75.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), txtContent.getFont().getStyle(), (int) ((int) FONT_SIZE*0.75)));
        }
    }//GEN-LAST:event_rbtn75ActionPerformed

    private void rbtn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn25ActionPerformed
        // TODO add your handling code here:
        if(rbtn25.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), txtContent.getFont().getStyle(), (int) ((int) FONT_SIZE*0.25)));
        }
    }//GEN-LAST:event_rbtn25ActionPerformed

    private void menuItemEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditTextActionPerformed
        // TODO add your handling code here:
        txtContent.setEditable(true);
    }//GEN-LAST:event_menuItemEditTextActionPerformed

    private void menuItemRemoveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRemoveTextActionPerformed
        // TODO add your handling code here:
        text = "";
        txtContent.setText(text);
    }//GEN-LAST:event_menuItemRemoveTextActionPerformed

    private void cbMenuItemUpperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenuItemUpperActionPerformed
        // TODO add your h
        if(cbMenuItemUpper.isSelected()){
            txtContent.setText(text.toUpperCase());
        }else{
            txtContent.setText(text.toLowerCase());
        }
    }//GEN-LAST:event_cbMenuItemUpperActionPerformed

    private void cbMenuItemBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenuItemBoldActionPerformed
        // TODO add your handling code here:
        if(cbMenuItemBold.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), Font.BOLD,FONT_SIZE ));
        }else{
            txtContent.setFont(new Font(txtContent.getFont().getName(), Font.PLAIN,FONT_SIZE ));
        }
    }//GEN-LAST:event_cbMenuItemBoldActionPerformed

    private void menuItemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRedActionPerformed
        // TODO add your handling code here:
        txtContent.setForeground(Color.red);
    }//GEN-LAST:event_menuItemRedActionPerformed

    private void menuItemBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBlueActionPerformed
        // TODO add your handling code here:
        txtContent.setForeground(Color.blue);
    }//GEN-LAST:event_menuItemBlueActionPerformed

    private void menuItemBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBlackActionPerformed
        // TODO add your handling code here:
        txtContent.setForeground(Color.black);
    }//GEN-LAST:event_menuItemBlackActionPerformed

    private void rbtn150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn150ActionPerformed
        // TODO add your handling code here:
        if(rbtn150.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), txtContent.getFont().getStyle(), (int) ((int) FONT_SIZE*1.5)));
        }
    }//GEN-LAST:event_rbtn150ActionPerformed

    private void rbtn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn100ActionPerformed
        // TODO add your handling code here:
        if(rbtn100.isSelected()){
            txtContent.setFont(new Font(txtContent.getFont().getName(), txtContent.getFont().getStyle(), (int) ((int) FONT_SIZE*1)));
        }
    }//GEN-LAST:event_rbtn100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupColor;
    private javax.swing.ButtonGroup btnGroupFontSize;
    private javax.swing.JCheckBoxMenuItem cbMenuItemBold;
    private javax.swing.JCheckBoxMenuItem cbMenuItemUnderline;
    private javax.swing.JCheckBoxMenuItem cbMenuItemUpper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem menuItemBlack;
    private javax.swing.JMenuItem menuItemBlue;
    private javax.swing.JMenuItem menuItemEditText;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemGreen;
    private javax.swing.JMenuItem menuItemRed;
    private javax.swing.JMenuItem menuItemRemoveText;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JRadioButtonMenuItem rbtn100;
    private javax.swing.JRadioButtonMenuItem rbtn125;
    private javax.swing.JRadioButtonMenuItem rbtn150;
    private javax.swing.JRadioButtonMenuItem rbtn25;
    private javax.swing.JRadioButtonMenuItem rbtn75;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
